services:
  - type: web
    name: job-aggregator-backend
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://sudhanshu-s3.github.io
      - key: RENDER
        value: true
    healthCheckPath: /
    plan: free # Consider upgrading to a paid plan for better resources
    autoDeploy: true
    pullRequestPreviewsEnabled: true
